import json

def load_data(file_path):
  """The function loads a json file with data about the animals."""
  with open(file_path, "r", encoding="utf-8") as handle:
    return json.load(handle)



def print_animals_info(animals):
    """The function iterates over the animals_data.json, collects and prints the name
    and, if included in the json data, prints also the diet, the first location entry,
    and the type of the fox-animal."""
    output = ''
    for animal_data in animals:
        output += '<li class="cards__item">'
        output += f"Name: {animal_data ["name"]}<br/>\n"

        characteristics = animal_data.get("characteristics", {})
        if "diet" in characteristics:
            output += f"Diet: {animal_data ["characteristics"] ["diet"]}<br/>\n"
        if "type" in characteristics:
            output += f"Type: {animal_data ["characteristics"] ["type"]}<br/>\n"

        locations = animal_data.get("locations", [])
        if locations:
            output += f"Location: {animal_data ["locations"][0]}<br/>\n"
            output += "</li>"
    return output


def read_html_template(file_path):
    """The function opens and reads the given html template with the placeholder string."""
    with open(file_path, "r", encoding="utf-8") as template:
        return template.read()


def create_animals_html(template, output_path, animals_info):
    """This function takes the template string, replaces the placeholder with
    the string generated by print_animals_info and saves result as animals.html  """
    new_html = template.replace("__REPLACE_ANIMALS_INFO__", animals_info)
    with open(output_path, "w", encoding="utf-8") as animals_html_file:
        animals_html_file.write(new_html)



def main():
    """Here is the main function that coordinates data collection, manipulation and output."""
    animals_data = load_data('animals_data.json')
    animals_info = print_animals_info(animals_data)
    template = read_html_template ("animals_template.html")
    create_animals_html(template, "animals.html", animals_info)
if __name__ == "__main__":
    main()
